### ISSUE TITLE
Some undefined terms and primitives

### ISSUE THREAD

**Issue by rozbb** [mlswg/mls-protocol#108]
I think a bunch of these are probably relics of previous versions. For reference, the page numbers listed are from the PDF version of draft 3 of the protocol:

- [x] 1 - p6: `GroupInit` is mentioned, but it is not defined anywhere in the specification. Perhaps `Init` is intended.

- [x] 2 - p19: A `transcript` field is mentioned, but only `transcript_hash` is present. Also it's unclear which `Hash` function is supposed to be used here. It can't be ciphersuite-dependent, since it has to be the same for every Participant.

- [x] 3 - p22: `update_secret` is used in a diagram, but never defined. I think this is important, and it's mentioned elsewhere.

- [x] 4 - p24: `finished_mac` is mentioned, but never defined. Is it supposed to say `confirmation`?

- [ ] 5 - p25: The underlying Hash that HMAC uses can't be defined by anyone's ciphersuite. This is group state, and everyone has to agree on this.

- [x] 6 - p28: Mentioned "update secret" again without explanation.

- [x] 7 - p29: "identity tree" is mentioned, but I can't tell what that's referring to. Also "update secret" is here.

- [x] 8 - p35: `MLSPlaintext` is mentioned, but never defined. Perhaps `ApplicationPlaintext` is intended.

**Comment by beurdouche** [comment]
Thanks a lot for the review, this is very useful.
I have a pass planned for this week and will fix these issues :)

**Comment by beurdouche** [comment]
@rozbb A PR #126 was opened with fixes for points 1, 2, 4, 7. Point 8 was already solved.
An issue has been opened #125 to solve points 3 and 6 related to the update secret definition.
I tried to figure out your point 5 but I didn't understand it, can you give details ?

**Comment by rozbb** [comment]
Sorry for the delay. I think point 5 was a misunderstanding over when a common ciphersuite is established in the protocol. I'm still not 100% clear on it, but I think I'm just missing something simple. Consider it withdrawn.

**Comment by beurdouche** [comment]
Ok, then these issues are fixed by #126 and #125. Thanks
